version: "3.8"
#
# Services definitions
#
services:
  app:
    image: kooldev/php:8.1-nginx
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  database:
    image: postgres:13-alpine
    ports:
      - "${KOOL_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE-database}"
      POSTGRES_USER: "${DB_USERNAME-user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD-pass}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - database:/var/lib/postgresql/data:delegated
    networks:
      - kool_local
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "$DB_DATABASE", "-U", "$DB_USERNAME"]
  cache:
    image: redis:6-alpine
    volumes:
      - cache:/data:delegated
    networks:
      - kool_local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  node:
    image: kooldev/node:16
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
#
# Networks definitions
#
networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  database:
  cache:
